# Generated by Django 5.2.11 on 2026-03-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_response_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_update_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('SELLER_UPDATED', 'Seller Updated'), ('CHANGES_REQUESTED', 'Changes Requested'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='REQUESTED', max_length=30),
        ),
    ]
