# Generated by Django 5.2.11 on 2026-04-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_buyer_response_note_order_buyer_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('REQUEST_ACCEPTED', 'Request Accepted'), ('REQUEST_REJECTED', 'Request Rejected'), ('SELLER_UPDATED', 'Seller Updated'), ('CHANGES_REQUESTED', 'Changes Requested'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='REQUESTED', max_length=30),
        ),
    ]
